### PR TITLE
LabJack T7 controller module

### PR DESCRIPTION
**Pull request by zykure**
This adds support for the **LabJack T7** hardware. Code is based on the existing U6 module.

The LabJack model was upgraded to use the new Modbus API. The code is contained in the `orca_t7.*` files, which provide interfaces to the ORCA classes. The GUI was slightly extended, e.g. it is now possible to select the analog I/O resolution and input range. The "probe" button now also selects any connected device automatically, if no device id has been entered. The new "poll now" button reads values from the T7 once, and the device-internal RTC is shown at the bottom of the controller window.

The T7 controller has some new features: 2 additional analog channels to read internal device temperature and noise level, additional digital I/O channels, 2 more counters, PWM output. (Counters and PWM have not been fully tested due to limited testing equipment.) One could also add clock output, which the T7 provides, but this hasn't been done in the ORCA module yet.

LabJack libraries were added/updated (libusb 1.0 and libLabJackM 1.20) to support the T7.

LabJack T7

### CODE REVIEW

**Review by tcald — CHANGES_REQUESTED** [review]
Thanks Jan.  Looks pretty good.  A couple of comments:

1) In Libraries/labjack you've added libusb-1.0.0.dylib.  There is a static version of libusb in Libraries/libusb.  Do we need the dynamic library you've added?  Can you check if the static version of libusb already in Orca will work for the labjack update?

2) I get a runtime error when trying to link libLabJackM-1.20.0.dylib:

dyld: Library not loaded: build/release/libLabJackM-1.20.0.dylib
  Referenced from: /Users/tcald/Library/Developer/Xcode/DerivedData/Orca/Build/Products/Development/Orca.app/Contents/MacOS/Orca
  Reason: image not found

Could you look into why it is producing this error?  Looking at the library with otool, it seems this is coming from a system dependent path in this load command:

Load command 3
          cmd LC_ID_DYLIB
      cmdsize 64
         name build/release/libLabJackM-1.20.0.dylib (offset 24)
   time stamp 1 Wed Dec 31 19:00:01 1969
      current version 1.20.0
compatibility version 1.20.0

**Comment by zykure** [comment]
Hey Tom, I looked into this but it seems pretty complicated.

First of all, the libraries have some hardcoded paths/ids. This can be changed with `install_name_tool -id | -change` on MacOS. Looking at other libs, I found that the load path should point to `@loader_path/../Frameworks`. This should make sure that the libLabJackM correctly loads the libusb.

Secondly, the libraries also needs to be placed in the `Frameworks` directory during installation. This is done for some libs (e.q. libmysqlclient) but not for all. For the MySQL lib, there are some references in the Xcode project file to something called `Frameworks_Copy`, but I failed to include the LabJack libs because I don't fully understand what's going on. It seems that handling dynamic libs is pretty difficult.

I don't have a static version of the libLabJackM because it wasn't provided by LabJack, so hopefully there's a way to fix this. I think what's missing is just to place the libusb in the Frameworks directory.

**Comment by zykure** [comment]
I think I fixed it by correcting the load paths and adding the files to the Frameworks directory. The code still build and runs after I removed my local files from the LJM library.

StackOverflow was extremely helpful with this, see these answers for reference:
* https://stackoverflow.com/questions/19776571/error-dlopen-library-not-loaded-reason-image-not-found/22560206#22560206
* https://stackoverflow.com/questions/1371351/add-files-to-an-xcode-project-from-a-script/1371595#1371595

**Comment by tcald** [comment]
Thanks Jan.  That seems to have fixed the problem.

One more question.  In the Analog Out part of the T7 interface, there are 2 sliding scales for the output voltage.  It seems that adjusting the top one for channel 0 changes the value displayed for channel 1 and vice versa.  Can you check that those are adjusting the correct displayed value in the interface and then linking to the right channel in the model?

**Comment by zykure** [comment]
Good catch! It was an issue in the interface, where the outlet connections were wrong. I also fixed a similar issue with the counter-resets. The model/controller code is correct; I checked all the aOut0/aOut1 methods for accidental mismatches.

**Comment by tcald** [comment]
Thanks Jan.  Looks good to me.

**Pull request merged**
